### ISSUE TITLE
GPU OpenCL debugger?

### ISSUE THREAD

**Issue by hughperkins** [jrprice/Oclgrind#94] opened 2016-06-04 20:40 UTC
Hi,

I'm writing a paper about cltorch, and was asserting that there are no portable OpenCL debuggers available for discrete GPUs.  But a bit of googling around came up with Oclgrind, which looks like it might very well go a very long way towards being exactly this in a sense?  To what extent is it possible to use Oclgrind to simulate arbitrary discrete GPU devices?  You say:

"This device exhibits the properties of the OpenCL execution model; it has four distinct memory address spaces and is aware of work-items, work-groups and the various execution and synchronisation constructs available within OpenCL. The simulation does not model any architecture specific properties such as SIMD execution or cache hierarchies. "

It sounds like you can simulate arbitrary workgroup sizes, local memory sizes and so on?  Any limitations to be aware of?  To what extent can it simulate running on for example Intel hd integrated gpus, NVIDIA discrete gpus, or AMD discrete gpus?  Presumably it wont detect vendor-specific compiler issues, nor performance issues, but it could detect logic errors that manifest for specific workgroupsizes or warp sizes perhaps?

**Comment by jrprice** [comment] 2016-06-04 23:14
> To what extent can it simulate running on for example Intel hd integrated gpus, NVIDIA discrete gpus, or AMD discrete gpus? Presumably it wont detect vendor-specific compiler issues, nor performance issues, but it could detect logic errors that manifest for specific workgroupsizes or warp sizes perhaps?

At present, Oclgrind will not simulate anything specific to any particular piece of hardware, so that includes the notion of warp/wavefront execution. This means that if you have code that exhibits a problem on a particular piece of hardware due to the specific way that this hardware schedules work-items (e.g. in a warp), then it's possible that Oclgrind will not spot the issue.

At some point in the future I intend to look at adding support for subgroups, which will go some way towards capturing the notion of warps/wavefronts. This would allow a user to select the subgroup size that they wish to simulate.

All that said, things like warps give additional guarantees that the OpenCL spec doesn't (e.g. lockstep execution allowing local memory to be shared within a warp without additional synchronisation), but the converse isn't true. This means that if you have some code that works on one platform but not on another because you're assuming behaviour that the specification doesn't guarantee, then Oclgrind *should* spot it. I'd always be interested to hear about specific problems that anyone encounters that Oclgrind doesn't catch.

**Comment by hughperkins** [comment] 2016-06-05 07:22
Hi James,

1. Oclgrind warpsize

> At present, Oclgrind will not simulate anything specific to any particular piece of hardware, so that includes the notion of warp/wavefront execution. [...] All that said, things like warps give additional guarantees that the OpenCL spec doesn't (e.g. lockstep execution allowing local memory to be shared within a warp without additional synchronisation)

Ok, understood.  Note that many kernels do in fact make use of knowledge of warps, in order to obtain the highest performance.  For example https://github.com/torch/cutorch/blob/f545703cf2ba602b4f9c7d4c7d53e3ef4f159dbb/lib/THC/THCSortUtils.cuh#L56 and https://github.com/torch/cutorch/blob/f545703cf2ba602b4f9c7d4c7d53e3ef4f159dbb/lib/THC/THCScanUtils.cuh#L60-L97

Typically such code is the exact same code which is trickiest to debug, and where I would most appreciate a debugger :-)

That said I do have some code that has a bug in it, that only manifests on AMD devices.  I dont have an AMD device, so have not been able to reproduce or fix the issue.  So I might dabble in seeing if Oclgrind lets me simulate/fix the issue on AMD.  I can use this as a prototype to understand what oclgrind can/cant do, in terms of debugging/fixing OpenCL issues.  This issue https://github.com/hughperkins/cltorch/issues/70

2. OpenCL debuggers in general

In other news, in terms of running a debugger against an actual discrete GPU, and this is totally out of the scope of ocgrind, but just in case you happen to know :-) , is it fair to say that there are no cross-platform debuggers available currently?  Is it fair to say that creating a cross-platform debugger for OpenCL devices would need some additional api functions to be created by Khronos?

**Comment by hughperkins** [comment] 2016-06-05 17:32
Ok, for now I have written: "When using CUDA, there are extensive debugging tools available, to facilitate finding root cause on kernel crashes, or numerical accuracy issues. When using OpenCL on CUDA devices, no such debugging tools are available. Some vendors provide debugging tools for their specific hardware. For example AMD has created CodeXL[2]. However, no cross-platform tool is available. An alternative approach is to use a simulator. Oclgrind [30] provides OpenCL kernel debug-
ging, using a simulated OpenCL device, loadable via ICD."

**Comment by UniqueFool** [comment] 2016-06-06 09:30
FWIW, there's the opencl-stress repository that has a collection of kernels that will help stress-test (or even crash) OpenCL: https://github.com/eholk/opencl-stress

I would agree that CUDA tooling seems much better than opencl tooling currently - a paper emphasizing that and suggesting ways to address this problem would be interesting actually.

> Presumably it wont detect vendor-specific compiler issues, nor performance issues, but it could detect logic errors that manifest for specific workgroupsizes or warp sizes perhaps?

Speaking in general, the kind of tool you seem have in mind would probably be best implemented as some kind of hybrid between oclgrind and a vhdl simulator, i.e. oclgrind implemented on top of a vhdl framework, so that different kinds of architectures can be simulated in the form of VHDL specs, that are then mapped to the ICD for OpenCL testing.

**Comment by hughperkins** [comment] 2016-06-06 09:32
> Speaking in general, the kind of tool you seem have in mind would probably be best implemented as some kind of hybrid between oclgrind and a vhdl simulator, i.e. oclgrind implemented on top of a vhdl framework, so that different kinds of architectures can be simulated in the form of VHDL specs, that are then mapped to the ICD for OpenCL testing.

That sounds like a ton of effort.  I think implementing `warpSize` would go a long way towards making oclGrind a useful debugging tool :-)

**Comment by hughperkins** [comment] 2016-06-06 09:35
(by the way, I did try to debug my port of `sort` to OpenCL, ie this kernel https://github.com/hughperkins/cltorch/blob/add-sort/src/lib/THClSortUtils.cl , which is called from https://github.com/hughperkins/cltorch/blob/add-sort/src/lib/THClTensorSort.cpp#L254  .  It looks like you've done a whole bunch of the hard bits.  Just that this kernel does use warpsize, ie https://github.com/hughperkins/cltorch/blob/add-sort/src/lib/THClSortUtils.cl#L75 , and therefore generates a ton of warnings, and the wrong results, currently :-) )

**Comment by UniqueFool** [comment] 2016-06-06 09:41
> That sounds like a ton of effort.  

as far as I can see, it's basically the route that Altera is using, which is why they can provide support for emulating devices and debuggging opencl code.

besides, implementing wavefront and warp size does come with tons of implications for memory layout/handling - I am not sure if it's too realistic/feasible to expect vendor-specifics to be convered by a general framework, especially given the number of driver-level issues (bugs) and internals that are not even exposed - sometimes, even the nvidia/cuda drivers exhibit hugely unexpected behavior in between version changes on the same hardware/OS.

**Comment by hughperkins** [comment] 2016-06-06 09:48
> especially given the number of driver-level issues (bugs) and internals that are not even exposed - sometimes, even the nvidia/cuda drivers exhibit hugely unexpected behavior in between version changes on the same hardware/OS.

Most bugs I've seen have been during compilation, eg AMD doesnt accept certain syntax for using structs (though it could plausibly be my own syntax that is wrong...).  Performance varies dramatically across devices.  workgroup sizes vary dramatically.  But I havent in general come across any noticeable bugs, once compilation has completed successfully.  I'm sure there are some, but in practice, it is not a painpoint for me.

Is it the case that the bug in`sort` that manifests only on AMD devices is a bug with the underlying AMD driver?  I dont know...  I suspect its just some logic bug in my own code, that is hidden somehow on nvidia geometry, but becomes apparent on AMD geometry.

I'm sure that implementing warpsize wont make your debugger usable on 100% of bugs, but it might handle the 99% of cases, where currently I put [this nonsense](https://github.com/hughperkins/cltorch/blob/7f0242f4b433874b15611f5491f985e775dcbd17/src/lib/THClSortUtils.cl#L156-L164) in my code, to find out what's happening.

**Comment by hughperkins** [comment] 2016-06-06 10:42
Oh, just noticed I wasnt responding to James.  Interesting.

> http://developer.amd.com/tools-and-sdks/opencl-zone/opencl-emulator-debugger/

It seems that this would need Visual Studio to run?  I'm using linux.

**Comment by UniqueFool** [comment] 2016-06-06 11:08
As far as I understand, an increasing number of ICD back-ends tend to use LLVM these days, I think that even applies to the nvidia ICD (nvptx): http://llvm.org/devmtg/2011-11/Holewinski_PTXBackend.pdf

Thus, a cross-platform open source OpenCL debugging environment could probably greatly benefit from the LLVM tooling already available

**Comment by jrprice** [comment] 2017-07-12 13:57
Closing as there isn't a specific addressable issue here (there are specific issues that have been raised separately as a result).

**Closed by jrprice** 2017-07-12 13:57 UTC
