### ISSUE TITLE
global pointer with non-global pointer comparison crashes

### ISSUE THREAD

**Issue by daniel-starke** [jrprice/Oclgrind#143] opened 2017-09-02 21:04 UTC
Using 16.10 I workaround the missing NULL define with the following macro:
`#define NULL ((void *)0)`
Comparing a global pointer with this resulted in a crash. Comparing the global pointer with just 0 worked.

**Comment by jrprice** [comment] 2017-09-03 11:10
Thanks for the report - I can reproduce this with 16.10, and also with the latest Oclgrind sources using LLVM 3.9 or 4.0.0. This seems to be the result of a bug in LLVM, which is fixed in 4.0.1 and 5.0.

**Comment by jrprice** [comment] 2018-03-09 11:29
Oclgrind 18.3 has been released and binaries are built with LLVM 6.0, so this bug should be fixed:
https://github.com/jrprice/Oclgrind/releases

**Closed by jrprice** 2018-03-09 11:29 UTC
