### ISSUE TITLE
linker error building with cmake on OS X

### ISSUE THREAD

**Issue by reuk** [jrprice/Oclgrind#84] opened 2016-02-23 23:44 UTC
I'm on OS X 10.11.3 using llvm 3.6.2 from homebrew, I get some 'undefined symbol' errors when building with cmake.

setup:

```
mkdir -p build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DLLVM_DIR=/usr/local/Cellar/llvm/3.6.2/share/llvm/cmake .. && make
```

error:

```
Undefined symbols for architecture x86_64:
  "std::runtime_error::what() const", referenced from:
      oclgrind::FatalError::what() const in common.cpp.o
  "std::out_of_range::~out_of_range()", referenced from:
      std::__1::unordered_map<llvm::Function const*, oclgrind::InterpreterCache::Builtin, std::__1::hash<llvm::Function const*>, std::__1::equal_to<llvm::Function const*>, std::__1::allocator<std::__1::pair<llvm::Function const* const, oclgrind::InterpreterCache::Builtin> > >::at(llvm::Function const* const&) const in WorkItem.cpp.o

...plus some more
```

All the stuff it can't find is from the stdlib, could this be some weirdness to do with using a non-system clang?

**Comment by jrprice** [comment] 2016-09-11 21:22
I've finally got round to taking a look at this, but I haven't been able to reproduce the issue that you've described. I'm on OS X 10.11.6, and using Homebrew's LLVM 3.6.2 I was able to build and run Oclgrind just fine, using both system Clang and the Homebrew version.

I guess the Homebrew package must have been updated since you last tried, since the path I had to give CMake was `/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/share/llvm/cmake/`.

Can you let me know if this is still an issue for your set-up? Sorry for taking so long to look at this.

**Comment by jrprice** [comment] 2017-07-12 13:58
Closing - seems to be fixed in Homebrew.

**Closed by jrprice** 2017-07-12 13:58 UTC
