### ISSUE TITLE
Oclgrind crashes with error "/usr/bin/oclgrind: line 145"

### ISSUE THREAD

**Issue by fangq** [jrprice/Oclgrind#145] opened 2017-10-11 18:59 UTC
I installed oclgrind on Ubuntu 16.04, and tried to debug a kernel for Intel ocl, however it crashed during the simulation

here are the commands to reproduce the issue

```
git clone https://github.com/fangq/mcxcl.git
cd mcxcl/src
make
cd ../example/benchmark
../../bin/mcxcl -L
oclgrind ../../bin/mcxcl -A -f benchmark1.json -b 1 -P '{"Shapes":[{"Sphere":   {"Tag":2, "O":[30,30,30],"R":15}}]}' -s benchmark2 -k ../../src/mcx_core.cl -n 1e6
```

the last command gave me an error

`/usr/bin/oclgrind: line 145:  7204 Killed                  LD_LIBRARY_PATH=$LIBDIR:$LD_LIBRARY_PATH LD_PRELOAD=$LIBDIR/liboclgrind-rt.so "$@"
`

wondering if you have any pointer on a work-around to this issue?

thanks

**Comment by jrprice** [comment] 2017-10-11 19:53
I can't reproduce this at the moment. If I run with fewer photons (e.g. `-n 100`), it seems to complete successfully. Does that work for you, or does it still crash?

Your error looks a bit like it is running out of memory and being killed by the OS. It's possible that there's a memory leak somewhere that is causing this - it does look like the memory usage is creeping up during the run.

**Comment by fangq** [comment] 2017-10-12 03:25
did you try "-n 1e6"? it can take a minute or so to see the crash.

when running 1e4 and 1e5, oclgrind did compete without any error on my Ubuntu box too, but 1e6 starts to crash. on my machine, I have 32GB memory and did not see a noticeable jump in memory usage.

**Comment by jrprice** [comment] 2017-10-13 08:37
Yes, I can reproduce this with `-n 1e6`. It definitely looks like it is running out of memory.

The issue is that Oclgrind only reports a single compute unit, which means your code only launches a single work group to do all of the work. Oclgrind allocates some memory while processing instructions that only gets released when a work-item completes, which is what is causing the problem.

There is a work-around - modify the code so that it launches a much larger number of work-groups. For example, if I set `cuinfo.sm=1024` inside `mcx_host.cpp` instead of using the value from `CL_DEVICE_MAX_COMPUTE_UNITS`, it runs to completion with `-n 1e6`. We could add a flag to Oclgrind to control how many compute units it reports to the application to make this easier.

BTW, if I run with a smaller number of compute units (e.g. 8), Oclgrind reports an out of bounds memory access like this:
```
Invalid read of size 4 at global memory address 0x10000000d5178
	Kernel: mcx_main_loop
	Entity: Global(232,0,0) Local(8,0,0) Group(7,0,0)
	  %79 = load i32, i32 addrspace(1)* %arrayidx74, align 4, !dbg !215
	At line 444 (column 23) of input.cl:
	  mediaid=media[idx1d];
```

**Comment by fangq** [comment] 2017-10-17 04:20
thank you @jrprice, just saw your reply. the explanation makes sense. 

no need to change source code, you can manually define work-group size using the -T option. I rerun the command by replacing -A with -t thread_num -T workgroup_size , I no longer see the crash, but the command was very slow, and the memory usage was significant.

glad to know oclgrind picked up this memory access bug, I eventually found out this bug using printf, and a fix was posted about 5 days ago. wish I had knew the workaround. 

https://github.com/fangq/mcxcl/commit/29bbf05558bd12e1ee51c04934dc3c81594eeeaa#diff-3e7bff849d973dfbbbf2ff6591ee8862

**Comment by jrprice** [comment] 2017-10-17 10:46
> but the command was very slow, and the memory usage was significant.

Yes, unfortunately the way the Oclgrind emulates instruction execution will mean that it will always be much slower than any real OpenCL device. If the memory usage becomes a problem I imagine that increasing the number of work-groups even further might help a bit.

**Comment by fangq** [comment] 2017-10-25 15:58
@jrprice, just to make sure I understand your suggestion, by "increasing the number work-groups", you meant to reduce the size of the work-group (block) or increase the size, so that there are less workgroups? 

for example, if I run simulation with 1024 threads and 64 threads per block (or workgroup), what should I do decrease the memory use? make 64/block to 32? or make this number bigger, say to 256?

**Comment by jrprice** [comment] 2017-10-25 16:02
Yes, reduce the number of threads per block, which in turn means you will have more blocks (work-groups). Alternatively you could increase the total number of threads you use, which would also produce more groups.

So in your example, reducing from 64 threads per block down to 32 should help a bit.

**Comment by jrprice** [comment] 2018-10-29 21:42
I don't think there's any outstanding issues here, so closing this now.

As of 9782f85 there is now a `--compute-units` flag to change the number of compute units reported by the `clGetDeviceInfo(..., CL_DEVICE_MAX_COMPUTE_UNITS, ...)` query, which may have helped with the original issue.

**Closed by jrprice** 2018-10-29 21:42 UTC
